# Generated by Django 2.0.7 on 2018-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0002_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='govuser',
            options={},
        ),
        migrations.AlterModelOptions(
            name='institutionuser',
            options={},
        ),
        migrations.AlterField(
            model_name='topic',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
