# Generated by Django 2.0.7 on 2018-07-31 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visitor', '0003_auto_20180731_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyuser',
            name='bossname',
        ),
        migrations.RemoveField(
            model_name='companyuser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='bossname',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='govcodeurl',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='idback',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='idfront',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='provepicture',
        ),
        migrations.RemoveField(
            model_name='govuser',
            name='type',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='bossname',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='institudecodeurl',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='registergraph',
        ),
        migrations.RemoveField(
            model_name='institutionuser',
            name='type',
        ),
        migrations.AddField(
            model_name='companyuser',
            name='businessscope',
            field=models.CharField(blank=True, db_column='businessScope', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='companytype',
            field=models.CharField(blank=True, db_column='companyType', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='interest',
            field=models.CharField(blank=True, db_column='interest', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='realname',
            field=models.CharField(blank=True, db_column='RealName', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='registerorg',
            field=models.CharField(blank=True, db_column='registerORG', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='companyuser',
            name='registertime',
            field=models.CharField(blank=True, db_column='registerTime', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='govuser',
            name='govtype',
            field=models.CharField(blank=True, db_column='govType', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='govuser',
            name='idcard',
            field=models.CharField(blank=True, db_column='IDCard', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='govuser',
            name='interest',
            field=models.CharField(blank=True, db_column='interest', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='govuser',
            name='realname',
            field=models.CharField(blank=True, db_column='realName', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='institudeurl',
            field=models.CharField(blank=True, db_column='institudeUrl', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='institutionlevel',
            field=models.CharField(blank=True, db_column='institutionLevel', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='institutiontype',
            field=models.CharField(blank=True, db_column='institutionType', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='interest',
            field=models.CharField(blank=True, db_column='interest', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='institutionuser',
            name='realname',
            field=models.CharField(blank=True, db_column='realName', max_length=32, null=True),
        ),
    ]
